name: Deployment

concurrency: production

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
   # - name: install sshpass
    #  run: sudo apt-get update && sudo apt-get install -y sshpass
    - name: create .ssh
      run: mkdir  ~/.ssh
    - name: test
      run: ls -l ~/.*
    - name: idrsa
      run: sudo touch ~/.ssh/id_rsa    
         # echo "${{ secrets.UNIV_RSA }}" > ~/.ssh/id_rsa
          #chmod 600 ~/.ssh/id_rsa
    - name: idrsa end
      run: sudo chmod 777 ~/.ssh/id_rsa 
    - name: idrsa_end2
      run: echo "${{ secrets.UNIV_RSA }}" > ~/.ssh/id_rsa
    ###############
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
         host: docketu.iutnc.univ-lorraine.fr
         username: ${{ secrets.UNIV_LOGIN }}
         password: ${{ secrets.UNIV_PASSWORD }}
         port: 22
         script: docker pull thomasrbn/ccd_infra_api
    ###############
    #- name: keyscan
     # run: ssh-keyscan -H "docketu.iutnc.univ-lorraine.fr" >> ~/.ssh/known_hosts
    #- name: connect ssh
     # run: sudo ssh ${{ secrets.UNIV_LOGIN }}@docketu.iutnc.univ-lorraine.fr -i ${{ secrets.UNIV_RSA }}
      #@ docker pull thomasrbn/ccd_infra_api
    
