name: Deployment

concurrency: production

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
   # - name: install sshpass
    #  run: sudo apt-get update && sudo apt-get install -y sshpass
    - name: create .ssh
      run: mkdir  ~/.ssh
    - name: test
      run: ls -l ~/.*
    - name: idrsa
      run: sudo touch ~/.ssh/id_rsa    
         # echo "${{ secrets.UNIV_RSA }}" > ~/.ssh/id_rsa
          #chmod 600 ~/.ssh/id_rsa
    - name: idrsa end
      run: sudo chmod 777 ~/.ssh/id_rsa 
          sudo echo ${{ secrets.UNIV_RSA }} > ~/.ssh/id_rsa
    
    - name: keyscan
      run: sudo ssh-keyscan -H docketu.iutnc.univ-lorraine.fr >> ~/.ssh/known_hosts
    - name: connect ssh
      run: sudo ssh ${{ secrets.UNIV_LOGIN }}@docketu.iutnc.univ-lorraine.fr -i ${{ secrets.UNIV_RSA }}
      #@ docker pull thomasrbn/ccd_infra_api
    
