name: ssh command
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: ssh
        uses: invi5H/ssh-action@v1
        env:
          SSH_HOST: docketu.iutnc.univ-lorraine.fr
          #SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.UNIV_LOGIN }}
          SSH_KEY: ${{ secrets.UNIV_RSA }}
     # - run: ssh ${{ steps.ssh.outputs.SERVER }} pwd

          
      - name: test 
        run: ssh docker pull thomasrbn/ccd_infra_api
