name: Deploy to Digital Ocean

on:
  push:
    branches:
      - master
    paths:
      - 'infraAPI/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_LOGIN }}
          password: ${{ secrets.HUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --tag thomasrbn/ccd_infra_api:latest
        working-directory: infraAPI/

      - name: Docker Build & Push to Docker Hub
        uses: timzu/github-actions-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.HUB_LOGIN }}
          PASSWORD: ${{ secrets.HUB_PASSWORD }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "thomasrbn/ccd_infra_api"
          TAG_NAME: "latest"
          LATEST: "true"

      - name: SSH into Digital Ocean droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.DROPLET_SSH_PORT }}

      - name: Deploy Docker container
        run: |
          ssh $DROPLET_USERNAME@$DROPLET_IP -p $DROPLET_SSH_PORT 'docker pull thomasrbn/ccd_infra_api'
