name: Deployment

concurrency: production

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:

      - name: SSH Action
  # You may pin to the exact commit or the version.
  # uses: invi5H/ssh-action@ece33b57060e562f8d17b6c20b715de95204bbf2
        uses: invi5H/ssh-action@v1.0.0
        with:
          # A unique name for the server
          NAME: docketu.iutnc.univ-lorraine.fr
          SSH_USER: ${{ secrets.UNIV_LOGIN }}
          # The hostname or the IP address
          SSH_HOST: docketu.iutnc.univ-lorraine.fr
          # The SSH port
          #SSH_PORT: # optional, default is 22
          # The full string SSH key
          SSH_KEY: ${{ secrets.UNIV_RSA }}
      - name: test 
        run: ssh docker pull thomasrbn/ccd_infra_api
