name: Symfony

on:
    push:
        branches: [ "infraAPI" ]
    pull_request:
        branches: [ "master" ]

permissions:
    contents: read

jobs:
    symfony-tests:
        runs-on: ubuntu-latest
        services:
            mariadb:
                image: mariadb:latest
                env:
                    MYSQL_ROOT_USER: root
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_USER: admin
                    MYSQL_PASSWORD: admin
                ports:
                    - 3306:3306
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
              with:
                  php-version: '8.3'
            - uses: actions/checkout@v3
            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-
            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --working-dir=infraAPI
            - name: Run Symfony Tests
              run: php infraAPI/bin/console doctrine:database:create --if-not-exists